# Generated by Django 2.2.6 on 2021-04-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210402_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку или фото', null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
